const fs=require('fs'),path=require('path'),{Parser}=require('htmlparser2');const {root,local}=require('./inventory.cjs');const manifest=require(path.join(root,'_data/image_assets.json'));
function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(x=>x.isDirectory()?walk(path.join(p,x.name)):[path.join(p,x.name)]);}
function list(s){return s.split(',').map(x=>{const m=x.trim().match(/^(.*)\s+(\d+(?:\.\d+)?)([wx])$/);return m?{url:m[1],n:Number(m[2]),unit:m[3]}:{url:x.trim(),n:1,unit:'x'}});}
function cssWidth(sizes,width){for(const s of sizes.split(',')){const text=s.trim(),m=text.match(/^\(min-width: (\d+)px\) (.*)$/);if(m&&width<Number(m[1]))continue;const v=m?m[2]:text;if(v.startsWith('calc('))return width-40;if(v.endsWith('vw'))return width*parseFloat(v)/100;if(v.endsWith('px'))return parseFloat(v);}throw Error(sizes)}
function pick(candidates,target){return candidates.find(x=>x.n>=target)||candidates.at(-1)}
function length(url){const p=local(url);if(!p)throw Error(url);return fs.statSync(path.join(root,p)).size;}
const scenarios=[];
for(const [name,width,dpr] of [['desktop-1440-dpr2',1440,2],['mobile-390-dpr2',390,2]]){const old=new Set(),next=new Set(),pages=[];for(const file of walk(path.join(root,'_site')).filter(x=>x.endsWith('.html'))){let picture=null;const before=new Set(),after=new Set();const parser=new Parser({onopentag(tag,a){if(tag==='picture')picture={};if(tag==='source'&&a.type==='image/webp'&&picture)picture.source=a;if(tag==='img'&&a.src){let original=a.src;if(a.srcset)original=pick(list(a.srcset),dpr).url;const src=picture?.source;before.add(local(original)||original);const selected=src?pick(list(src.srcset),cssWidth(src.sizes,width)*dpr).url:original;after.add(local(selected)||selected);}if(tag==='video'&&a.poster){before.add(local(a['data-original-poster']||a.poster));after.add(local(a.poster));}},onclosetag(tag){if(tag==='picture')picture=null}});parser.write(fs.readFileSync(file,'utf8'));parser.end();if(file.endsWith('/index.html')&&path.relative(path.join(root,'_site'),file)==='index.html'&&width>1024){for(const h of Object.values(manifest.hover)){before.add(h.original);after.add(pick(list(h.srcset),cssWidth(h.sizes,width)*dpr).url)}}
for(const x of before)old.add(x);for(const x of after)next.add(x);pages.push({page:path.relative(path.join(root,'_site'),file),originalBytes:[...before].reduce((s,x)=>s+length(x),0),deliveredBytes:[...after].reduce((s,x)=>s+length(x),0)});}
const originalBytes=[...old].reduce((s,x)=>s+length(x),0),deliveredBytes=[...next].reduce((s,x)=>s+length(x),0);scenarios.push({name,width,dpr,originalBytes,deliveredBytes,savingsPercent:Number((100*(1-deliveredBytes/originalBytes)).toFixed(2)),pages,notes:'Calculated unique image URLs across the full site after scrolling; assumes WebP support and browser selection from authored sizes, with all hover states visited on desktop and hidden hover media excluded on mobile. Does not include video payloads.'});}
fs.writeFileSync(path.join(__dirname,'reports/responsive-budgets.json'),JSON.stringify(scenarios,null,2)+'\n');console.log(JSON.stringify(scenarios.map(({pages,...x})=>x),null,2));
